default_charset = "UTF-8"
expose_php = Off
mbstring.language = Korean
mbstring.internal_encoding = UTF-8
date.timezone = Asia/Seoul

upload_max_filesize = 20M
post_max_size = 24M
memory_limit = 256M
max_execution_time = 120

display_errors = Off
log_errors = On
error_reporting = E_ALL

session.cookie_httponly = 1
session.cookie_samesite = Lax
session.use_strict_mode = 1
